### PR TITLE
Add method to find mutual friends

### PR DESCRIPTION
**Pull request by clarkewing**
Adds $user1->getMutualFriends($user2)
Adds $user1->getMutualFriendsCount($user2)

A little sloppy but it works!

### CODE REVIEW

**Comment by hootlex** [comment]
Nice! Can you provide some tests?

**Comment by stephane-monnot** [comment]
@clarkewing Do you plan to continue the development of this interesting feature ? If you need help for testing, ask me or ask @hootlex. I'm looking forward to this feature :)

**Comment by hootlex** [comment]
@clarkewing Merged in https://github.com/hootlex/laravel-friendships/pull/39. 
Thanks for your contribution.

**Comment by clarkewing** [comment]
Sorry guys, I was offline for a little while.
Anyways, I see @stephane-monnot took care of adding tests and documentation. Thanks a lot, I really appreciate it!

**Comment by stephane-monnot** [comment]
@clarkewing It has been a great pleasure :)

**Pull request closed without merging**
