### PR TITLE
Fix composer error on build

### PR DESCRIPTION
**Pull request by stephane-monnot**

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@hootlex I believe I understand, with the vendor cache, after change directory to run  `vendor/laravel/laravel` and run `composer install`, composer will create a composer.lock file. When we call `composer.install` next time, this will install from composer.lock, while the main project doesn't have composer.lock. So the packages installed may be not compatible. 

2 possibles solutions:
 - disable the cache on vendor
 - make composer update instead of composer install
 - remove composer.lock from vendor/laravel/laravel/composer.lock

**Comment by stephane-monnot** [comment]
It seems like something went wrong with the new laravel version. I will try on localhost.

**Comment by stephane-monnot** [comment]
@hootlex I reproduced the `Class 'Illuminate\Notifications\NotificationServiceProvider' not found` error on local. I fixed with a composer update. I will try this solution. 

I will create new PR for L5.3 support.

**Comment by hootlex** [comment]
@stephane-monnot
1. have you thought of deleting composer.lock within `after_script`?
2. Hotfixes should me merged on both branches, but currently, the dev branch is pretty messed up.
I think I will delete it and create a new one.
3. :heart:

**Comment by stephane-monnot** [comment]
@hootlex 
1. I wanted remove, but I don't like `rm` :smile: . So I thought, `composer install` without composer.lock = `composer update`.
2. Ok, check before if master is up to date :wink: .
3. :tada:

**Pull request merged**
