### PR TITLE
Improve the travis build

### PR DESCRIPTION
**Pull request by stephane-monnot**

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@hootlex You can review and merge. I added scrutinizer config file. Could you create a scrutinizer account, add `hootlex/laravel-friendships` and launch an inspection after merged (for the new badges in readme) ?

**Comment by hootlex** [comment]
Haven't heard of scrutinizer before. What about codeclimate.com?

**Comment by stephane-monnot** [comment]
I didn't use codeclimat, but it's the same i think. I have already created the conf file. Just to motivate people to contribute ;).

**Comment by hootlex** [comment]
I tried both today and code climate seems a bit more pleasant to use.
If you want I can merge the rest of the commits and config code climate myself. :)

Thanks for taking the time to do this, it is indeed motivating. :)

**Comment by hootlex** [comment]
Should I merge it?

**Comment by stephane-monnot** [comment]
Yes, i didn't have time to use codeclimat, if you have free time  ;) .

**Comment by hootlex** [comment]
Sure, thanks!

**Comment by hootlex** [comment]
@stephane-monnot wow that was HUGE!



If you want to, submit a PR to:
1. [laravel-moderation](https://github.com/hootlex/laravel-moderation)
2. [vuedo](https://github.com/Vuedo/vuedo)

**Comment by hootlex** [comment]
@stephane-monnot I've integrated code climate in [v1.0.20](https://github.com/hootlex/laravel-friendships/releases/tag/v1.0.20).

**Comment by stephane-monnot** [comment]
wow, good job ! coverage 97%, 4.0

**Comment by hootlex** [comment]
@stephane-monnot there is something going wrong with this setup https://travis-ci.org/hootlex/laravel-friendships/jobs/154911152

**Pull request merged**
