### PR TITLE
Pr/33 - group friendships

### PR DESCRIPTION
**Pull request by hootlex**

### CODE REVIEW

**Comment by hootlex** [comment]
@nikolaynesov I exported Group tests to another file since FriendshipsTest is becoming huge.
I splitted your tests into smaller ones to be more unit style. Also, I added more substantial assertions (check tests regarding group removal).

The bug I was talking about it was actually a wrong assertion in my tests. So, there is nothing to fix. Sorry. :)

What I suggest, is to create more tests before merging, since you have added a lot of new functions to the package.
If you don't like testing, I can write some tests for you. :)

Thanks for the work you've done so far!

**Comment by nikolaynesov** [comment]
hi @hootlex,

Thanks, I see you wrote some tests to separate file. Can I just take your file and add more functions and commit to my brunch. I added only 2 functions to the trait I think so I guess you want me to write tests for old functions that now support groups, right? I can do that for sure.

**Comment by hootlex** [comment]
1. I think you can just pull this pr but if you want to take the file, I got no problem, whatever makes you comfortable.
2. Yup, this is what I am talking about. :)

**Comment by nikolaynesov** [comment]
Ok, I pulled this branch to my local and pushed it to my master branch. I will add additional tests before Monday I think.

**Comment by hootlex** [comment]
Perfect, thanks!

Στις 13 Αυγ 2016 21:21, ο χρήστης "Nikolay" <notifications@github.com>
έγραψε:

**Pull request closed without merging**
