### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by nahid**

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@hootlex Could you make a new release from develop ? It's better.

**Comment by hootlex** [comment]
@nahid This is duplicate with https://github.com/hootlex/laravel-friendships/pull/45

**Comment by stephane-monnot** [comment]
@hootlex Maybe he thought that it will directly merge on master. It's why he makes new PR.

**Comment by hootlex** [comment]
@stephane-monnot Now that I see it again, I can't understand [this ](https://github.com/hootlex/laravel-friendships/pull/47/files#diff-6e94da5101815ea73b54bcb1ae657142R97).
The concept isn't to check if the recipient has a pending friend request? Is it the opposite?

**Comment by stephane-monnot** [comment]
@hootlex Yes, opposite. I didn't check the discussion. We already had `hasFriendRequestFrom`. The concept is "have Already Sent A Friend Request To".

**Comment by hootlex** [comment]
@stephane-monnot oh, I was totally confused and talking about the wrong method the whole time!!
Why u didn't say anything on my [suggestion](https://github.com/hootlex/laravel-friendships/pull/45#issuecomment-241415277)? :P

@nahid sorry man, what about naming the method `hasSentFriendRequest`?

**Comment by stephane-monnot** [comment]
@hootlex Didn't see it :stuck_out_tongue_winking_eye: . `hasSentFriendRequest` or `hasSentFriendRequestTo` ?

**Comment by hootlex** [comment]
`hasSentFriendRequestTo` :punch:

**Comment by nahid** [comment]
yes it will be `hasSentFriendRequestTo`

**Comment by stephane-monnot** [comment]
@hootlex /!\ the branch dev has already been merged with #45. Maybe `git cherry-pick` to get only 2 last commits on dev branch and after reviewing, merge dev with master ?

**Comment by nahid** [comment]
Thank you :)

**Comment by hootlex** [comment]
@nahid :smiley:

**Pull request merged**
