### PR TITLE
Added optional param to get friends method to be able to get a number of friends per page

### PR DESCRIPTION
**Pull request by shinbuntu**

### CODE REVIEW

**Comment by shinbuntu** [comment]
In the future, I think it will be a good idea if we change the visibility of the "getFriendsQueryBuilder" method to benefit from the power of the Eloquent Builder. 

What do you think about this ?

**Comment by hootlex** [comment]
Sure, it sounds good. It will be useful for extending queries with limit, order, etc.

I was thinking to rewrite the Friendable trait to use scopes in the future.

This way it could be used like this:
```php
$user->friends()->get();
$user->friends()->whereRole('moderator')->get();

$user->pendingFriendships()->get();
$user->pendingFriendships()->limit(10)->get();
```

But I am not sure if this will be useful or just a waste of time.
What do you think?

**Comment by shinbuntu** [comment]
It sounds good but it's not backward compatible. 

Actually, the friends method returns a morphMany relation of friendship: 
```php
return $this->morphMany(Friendship::class, 'sender');
```
But in your example, it seems you want to use a Friend Model scope: 
```php
$user->friends()->whereRole('moderator')->get();
```
Maybe a new major version is a good idea, isn't it ? 

If yes, I imagined a use like this for friendships (pending request) : 
```php
// requests from others users than me (incomingScope)
$user->friendships()->incoming(); 

// requests of current users to others users  (outgoingScope)
$user->friendships()->outgoing(); 
```
I don't know if we need to apply a default filter on status pending to friendships or not.  As you said, it could be better to create a pendingFriendships method. A bit too long name, but more explicite. Moreover, we keep the ability to get accepted and blocked friendships.

Or only use scope like this : 
```php
// all requests from others users than me (pending/accepted/blocked)
$user->friendships()->incoming(); 

 // requests of current users to others users  (pending/accepted/blocked)
$user->friendships()->outgoing();

 // requests of current users to others users  (only pending)
$user->friendships()->pending()->outgoing();
// just an alias of $user->friendships()->whereStatus(Status::PENDING)->outgoing()
```
Of course, we can also create pendingFriendships() method, an alias of 
```php
$user->friendships()->whereStatus(Status::PENDING);
```

**Comment by hootlex** [comment]
Yeah, it should be a major release since it demands a lot of work to make all these changes backwords compatible.

Of course we could make something like
```php
public function getPendingFriendships(){
    return $this->friendships()->pending()->get()
}
```

but it would be a pain!

In my scenario by `$user->friends()` I was referring to current `$user->getFriendsQueryBuilder()` function.

I like your idea. I believe `$user->friendships()->pending()` is much cleaner than `$user->pendingFriendships()`

Scopes `incoming()` and `outgoing()` seem a bit confusing but may be useful.

I cant decide if this package needs a major release :/  

For changes like these it has to be written almost from zero.

**Comment by shinbuntu** [comment]
The only problem is the friends() method, this may get confused because it will return a friend model instead of a friendship model as now.

Scopes ```incoming()``` and ```outgoing``` maybe need a vote. New major realease too :) .

**Comment by hootlex** [comment]
I think `friends` will be less confusing this way.

```php
//returns friendships
$user->friendships()->whatever()->get(); 

//returns friends
$user->friends()->get(); 
```

This package is too small to make a vote yet.
We have to decide :)

**Comment by hootlex** [comment]
What do you say about accepting/denying friend requests?

```php
//current way
$user->acceptFriendRequest($friend);
$user->denyFriendRequest($friend);


//possible new way
$user->friendships()->accept($friend);
$user->friendships()->deny($friend);

```

**Pull request merged**
