### PR TITLE
add new method isSentFriendRequest

### PR DESCRIPTION
**Pull request by nahid**
its too important to check is this user has already received friend request from me. So I just add a new method `isSentFriendRequest`

### CODE REVIEW

**Comment by stephane-monnot** [comment]
@nahid, Good idea. Could you provide some tests ? and update the readme file please ? 
For tests, you can see [this 2 tests following](https://github.com/nahid/laravel-friendships/blob/master/tests/FriendshipsTest.php#L78) and adapt.

**Comment by nahid** [comment]
Yes I already provide tests and update readme file. Please check this

**Comment by hootlex** [comment]
Thanks for contributing @nahid, good job!
I think the function name should be `hasPendingFriendRequest` to be clearer.

**Comment by nahid** [comment]
@hootlex I just changed the method name `isSentFriendRequest` to `hasPendingFriendRequest`

**Comment by hootlex** [comment]
@nahid thanks!

**Pull request merged**
