### PR TITLE
Firing events

### PR DESCRIPTION
**Pull request by davidavz**
As discussed in #54

### CODE REVIEW

**Comment by hootlex** [comment]
@davidavz Great job! Thanks!

**Comment by hootlex** [comment]
@davidavz what's the issue with `DatabaseTransactions`?
When enabled SQL timeouts... :@

**Comment by davidavz** [comment]
@hootlex Don't know what you mean :confused:

**Comment by hootlex** [comment]
Within the [test file](https://github.com/hootlex/laravel-friendships/pull/55/files#diff-ad9dc2072a751da7416f2fbb84eb8987R9), DatabaseTransactions is commented out.

When I enable it, it throws the following error when running the tests:
```
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: insert into `friendships` (`recipient_id`, `recipient_type`, `status`, `sender_type`, `sender_id`, `updated_at`, `created_at`) values (1147, App\User, 0, App\User, 1146, 2016-09-14 23:22:15, 2016-09-14 23:22:15))
```

**Pull request merged**
