### PR TITLE
Added three new methods for limit and pagination when getting Friends(accepted)

### PR DESCRIPTION
**Pull request by elsodev**
#### Get All Friends(accepted) (It returns a collection of friend models not friendships, for example User)
```php
$user->getAllFriends();
```

### Get Friends(accepted) with Limit 
```php
$user->getFriendsLimited($limit);
```
##### Use Case
```php
$user->getFriendsLimited(5);
```
This will return only 5 friends.

### Get Friends(accepted) with Pagination 
```php
$user->getFriendsWithPagination($perPage);
```

##### Use Case
```php
$friends = $user->getFriendsWithPagination(5);
```
This will return a paginator object. To render links
```
5.1: Use ->render();
5.2: Use ->links();
```
##### View
```html
@foreach($friends as $friend)
	<p>{{ $friend->name }}</p>
@endforeach

{!! $friends->links() !!}
```

### CODE REVIEW

**Comment by hootlex** [comment]
Thanks for the pr @elsodev.

I see that you have changed `getFriends` method to `getAllFriends`.
This change will break anyone's code who is currently using `getFriends`.
To limit the friends you can do something like  `getFriends($limit)` where `$limit` will be 0 by default so `getFriends()` will return all friends.

Feel free to add as many new tests as you want but please dont modify old ones that are failing after your changes.

**Comment by elsodev** [comment]
@hootlex ok sure, i will make some changes.

**Comment by hootlex** [comment]
@elsodev let me know when you are done.

**Comment by hootlex** [comment]
@elsodev should I close this pr?

**Comment by shinbuntu** [comment]
Do you plan to close this pr soon ?

**Comment by hootlex** [comment]
@shinbuntu this pr in unfinished.
If @elsodev doesnt complete it soon I will develop this feature myself.

**Comment by shinbuntu** [comment]
@hootlex I also thought like you. If I have time, I will do and make a new pull request. To keep backward compatibility, we should add new methods getSomethingQueryBuilder to be able to easily add limit, order and others sql clauses and keep the  getSomething methods unchanged.

**Comment by hootlex** [comment]
@shinbuntu exaclty! I was thinking to rewrite all the 'getSomething' functions so they could work more dynamically.

For example `getFriendRequests()` could change to `getFriendRequests($paginated = 0, $limit = 0, $offset = 0)`
where:
`getFriendRequests()` -> returns all friend requests
`getFriendRequests(10)` -> returns the friend requests paginated (10 per page)
`getFriendRequests(0, 10, 30)` -> returns 10 friend requests paginated (10 per page)

Is this what are you thinking too or you have a better idea? :)

I would be very happy if you do a pr since I am kinda busy these days.

**Pull request closed without merging**
